/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as EasyAccordionImport } from './routes/easy/accordion'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const EasyAccordionRoute = EasyAccordionImport.update({
  id: '/easy/accordion',
  path: '/easy/accordion',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/easy/accordion': {
      id: '/easy/accordion'
      path: '/easy/accordion'
      fullPath: '/easy/accordion'
      preLoaderRoute: typeof EasyAccordionImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/easy/accordion': typeof EasyAccordionRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/easy/accordion': typeof EasyAccordionRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/easy/accordion': typeof EasyAccordionRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/easy/accordion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/easy/accordion'
  id: '__root__' | '/' | '/easy/accordion'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EasyAccordionRoute: typeof EasyAccordionRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EasyAccordionRoute: EasyAccordionRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/easy/accordion"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/easy/accordion": {
      "filePath": "easy/accordion.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
